# このファイル内ではsecretsは扱えない
name: 'Set Up'
description: 'Set up the build environment'
inputs:
  release_build:
    description: 'Whether this is a release build'
    required: true
    default: true

outputs:
  build_time:
    description: 'The build number'
    value: ${{ steps.set-vers.outputs.build_time }}
  pkg:
    description: 'package name'
    value: ${{ steps.set-pkg.outputs.pkg }}

runs:
  using: "composite"
  steps:
  - name: Set build time
    id: set-vers
    run: |
      echo "branch name=${GITHUB_REF}"
      if [ "${{ inputs.release_build }}" = "true" ]; then
          suffix=""
      else
          suffix="-SNAPSHOT"
      fi
      # echo "build_time=$(date +%Y%m)-${GITHUB_REF#refs/heads/}${suffix}" | sed "s/\//-/g" >> $GITHUB_OUTPUT
      echo "build_time=hoge4${suffix}" | sed "s/\//-/g" >> $GITHUB_OUTPUT
    shell: bash

  - name: Set pkg
    id: set-pkg
    run: |
      if [ "${{ inputs.release_build }}" = "true" ]; then
        pkg="releases"
      else
        pkg="snapshots"
      fi
      echo "pkg=${pkg}.com.example.template_common" >> $GITHUB_OUTPUT
    shell: bash

  - name: Set up JDK 17
    uses: actions/setup-java@v3
    with:
      java-version: '17'
      distribution: 'temurin'
