name: 'Set Up'
inputs:
    release_build:
        required: true
        default: true

outputs:
    build_number:
        value: ${{ steps.set-vers.outputs.build_number }}

runs:
    using: "composite"
    steps:
        - name: Set variables
          id: set-vers
          run: |
            echo "branch name=${GITHUB_REF}"
            if [ "${{ inputs.release_build }}" = "true" ]; then
                suffix=""
            else
                suffix="-SNAPSHOT"
            fi
            echo "build_time=$(date +%Y%m)-${GITHUB_REF#refs/heads/}${suffix}" | sed "s/\//-/g" >> $GITHUB_OUTPUT
        shell: bash

        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
          java-version: '17'
          distribution: 'temurin'
