name: snapshot build

on: 
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: none

    steps:
      # Set Up前にcheckout必要
      - uses: actions/checkout@v3

      - name: Set Up
        id: setup
        uses: ./.github/workflows
        with:
          release_build: false

      - name: Build with Maven
        run: mvn --settings ./settings.xml clean install -Dbuild_time=${{ steps.setup.outputs.build_time }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: src
          path: .

  test:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: none
      packages: none

    steps:
      # Set Up前にcheckout必要
      - name: Download checkout folder
        uses: actions/download-artifact@v3
        with:
          name: src
      
      - name: Set Up
        id: setup
        uses: ./.github/workflows
        with:
          release_build: false

      - name: Test
        run: mvn --settings ./settings.xml test -Dbuild_time=${{ steps.setup.outputs.build_time }}

  deploy:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: none
      packages: write

    steps:
      # Set Up前にcheckout必要
      - name: Download checkout folder
        uses: actions/download-artifact@v3
        with:
          name: src
      
      - name: Set Up
        id: setup
        uses: ./.github/workflows
        with:
          release_build: false

      - name: Deploy to GitHub Packages
        run: mvn --settings ./settings.xml deploy -Dbuild_time=${{ steps.setup.outputs.build_time }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  delete-old-package:
    # 直近３件のみ残す
    needs: deploy
    runs-on: ubuntu-latest
    permissions:
      contents: none
      packages: write

    steps:
      - name: Token発行（Github App）
        id: generate_token
        uses: tibdex/github-app-token@v1.8
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Token確認
        env:
          TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          echo "Access Token: ghs_"
          echo "Access Token: ${TOKEN:4}"

      - uses: actions/delete-package-versions@v4
        with: 
          package-name: 'releases.com.example.template_common'
          package-type: 'maven'
          min-versions-to-keep: 3
          delete-only-pre-release-versions: "true"
          token: ${{ secrets.DEL0905 }}
