name: kensho

on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: none

    steps:
    # Set Up前にcheckout必要
    - uses: actions/checkout@v3

    - name: Set Up
      id: setup
      uses: ./.github/workflows

    - name: Upload src
      uses: actions/upload-artifact@v3
      with:
        name: src
        path: .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: none
      packages: write

    steps:
    # Set Up前にsrc必要
    - name: Download checkout folder
      uses: actions/download-artifact@v3
      with:
        name: src
    
    - name: Set Up
      id: setup
      uses: ./.github/workflows

    - name: Github App token発行
      id: generate_token
      uses: tibdex/github-app-token@v1.8.2
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.PRIVATE_KEY }}

    - name: artifact list
      run: |
          # 削除にはactions write permissionが必要だったので、諦めた
          curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ steps.generate_token.outputs.token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/coding-sample/template_common/actions/artifacts

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: jar
        path: target/*.jar