name: release build

on: 
  push:
    branches-ignore:
      - xxx

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: none

    steps:
      # Set Up前にcheckout必要
      - uses: actions/checkout@v3

      - name: Set Up
        id: setup
        uses: ./.github/workflows

      - name: Build with Maven
        run: mvn --settings ./settings.xml clean install -Dbuild_time=${{ steps.setup.outputs.build_time }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: src
          path: .

  test:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: none
      packages: none

    steps:
      # Set Up前にsrc必要
      - name: Download checkout folder
        uses: actions/download-artifact@v3
        with:
          name: src
      
      - name: Set Up
        id: setup
        uses: ./.github/workflows

      - name: Test
        run: mvn --settings ./settings.xml test -Dbuild_time=${{ steps.setup.outputs.build_time }}

  delete-package:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: none
      packages: none

    steps:
      - name: Token発行（Github App）
        id: generate_token
        uses: tibdex/github-app-token@v1.8
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Token確認
        env:
          TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          echo "Access Token: ghs_"
          echo "Access Token: ${TOKEN:4}"

      # Set Up前にsrc必要
      - name: Download checkout folder
        uses: actions/download-artifact@v3
        with:
          name: src
      
      # build_time取得に必要
      - name: Set Up
        id: setup
        uses: ./.github/workflows

      - name: debug
        run: |
          echo "${{ github.repository }}"
          echo "----------"

      - name: パッケージ削除
        run: |
          # packageのバージョンIDを取得
          res=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ steps.generate_token.outputs.token }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/orgs/template-maven/packages/maven/releases.com.example.template_common/versions)
          echo "before ---"
          echo "${res}"
          echo "----------"
          id=$(echo "${res}" | jq '.[] | select(.name == "${{ steps.setup.outputs.build_time }}") | .id')
          echo "ID of package with name '${{ steps.setup.outputs.build_time }}' is: ${id}"

          # IDが存在しない場合、削除をスキップ
          if [ -z "${id}" ]; then
            echo "No ID found. Skipping deletion."
            exit 0
          fi

          # 削除
          echo "Deleting package with ID ${id}"
          curl -L \
            -X DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ steps.generate_token.outputs.token }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/orgs/template-maven/packages/maven/releases.com.example.template_common/versions/${id}

          # 削除確認
          res=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ steps.generate_token.outputs.token }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/orgs/template-maven/packages/maven/releases.com.example.template_common/versions)
          echo "after ---"
          echo "${res}"

        shell: bash

  deploy:
    needs: delete-package
    runs-on: ubuntu-latest
    permissions:
      contents: none
      packages: write

    steps:
      # Set Up前にsrc必要
      - name: Download checkout folder
        uses: actions/download-artifact@v3
        with:
          name: src
      
      - name: Set Up
        id: setup
        uses: ./.github/workflows

      - name: Deploy to GitHub Packages
        run: mvn --settings ./settings.xml deploy -Dbuild_time=${{ steps.setup.outputs.build_time }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
