name: release build for tag

on: 
  repository_dispatch:
    types: [trigger_chain]

jobs:
  trigger_next_build:
    runs-on: ubuntu-latest
    permissions:
      contents: none
      packages: none
    steps:
      - name: Trigger next repo build
        run: |
          CHAIN_JSON=($(echo '${{ toJson(github.event.client_payload.chain) }}' | jq -r '.[]'))
          WORKFLOW_FILE_NAME=${{ github.event.client_payload.workflow_file_name }}
          echo "Workflow file name is $WORKFLOW_FILE_NAME"
          TAG_NAME=${{ github.event.client_payload.tag_name }}
          CURRENT_REPO=$(echo "${{ github.repository }}" | cut -d'/' -f2)  # This will be 'maven_common'
          echo "Current repo is $CURRENT_REPO"

          NEXT_REPO_NAME=""
          FOUND_CURRENT=false

          echo "Chain is ${CHAIN_JSON[@]}"

          for REPO in $(echo $CHAIN_JSON | jq -r '.[]'); do
            if [ "$FOUND_CURRENT" = true ]; then
              NEXT_REPO_NAME=$REPO
              break
            fi
            if [ "$REPO" = "$CURRENT_REPO" ]; then
              FOUND_CURRENT=true
            fi
          done
          if [ -n "$NEXT_REPO_NAME" ]; then
            echo "Triggering workflow in $NEXT_REPO_NAME with file $WORKFLOW_FILE_NAME and tag $TAG_NAME"
            curl -X POST \
                -H "Authorization: token ${{ secrets.PKG_READ_ETERNAL }}" \
                -H "Accept: application/vnd.github.v3+json" \
                https://api.github.com/repos/coding-sample/$NEXT_REPO_NAME/actions/workflows/$WORKFLOW_FILE_NAME/dispatches \
                -d '{"event_type": "trigger_chain", "client_payload": {"chain": "'$(echo $CHAIN_JSON | jq -r '.[1:] | @csv')'", "workflow_file_name": "'$WORKFLOW_FILE_NAME'", "tag_name": "'$TAG_NAME'"}}'
          fi
